services:
  db:
    image: postgres:16
    container_name: projetsecret-db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - projetsecret_pgdata:/var/lib/postgresql/data
    networks:
      - projetsecret_net

  api:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: projetsecret-api
    working_dir: /src
    env_file: .env
    environment:
      - ConnectionStrings__Default=${CONNECTIONSTRINGS__DEFAULT}
      - JWT__Secret=${JWT_SECRET}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
    depends_on:
      - db
    ports:
      - "8080:5000"
    volumes:
      - ./api/ProjetSecret:/src:cached
    command: dotnet watch run --urls http://0.0.0.0:5000
    networks:
      - projetsecret_net

volumes:
  projetsecret_pgdata:

networks:
  projetsecret_net:
    driver: bridge
